name: Build App & Push to container registry

on: [push]
  
jobs:
    build-and-push-package:
        runs-on: ubuntu-latest
        env: 
          working-directory: .
        steps:
        - name: Checkout code
          uses: actions/checkout@master
          
        - name: Setup .NET ${ { env.DOTNET_VERSION } } Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'
            
        - name: Build Project
          run: dotnet build
            
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1.10.0
          with:
             registry: ghcr.io
             username: ${ { github.actor } };
             password: ${ { secrets.GITHUB_TOKEN } }
             
        - name: Build and push container package
          id: docker_build
          uses: docker/build-push-action@v2.7.0
          with:
            push: true
            context: ${ {env.working-directory} }
            tags: |
              ghcr.io/bjork-dev/blobapp2:latest
              ghcr.io/bjork-dev/blobapp2:${ { github.run_number } }
